Fixing issue ith env vars

diff --git a/dockerfile-builder.yaml b/dockerfile-builder.yaml
--- a/dockerfile-builder.yaml
+++ b/dockerfile-builder.yaml
@@ -63,22 +63,18 @@ setup:
         - composer.phar require --working-dir=/tmp/warmCache firegento/debug
         - composer.phar require --working-dir=/tmp/warmCache connect20/nexcessnet_turpentine
         - rm -rf /tmp/warmCache
-        # Sample data
+        # Download sample  data
         - mkdir -p $( dirname ${SETUP_CACHE_MAGENTO_SAMPLE_DATA_PATH})
         - curl -o $SETUP_CACHE_MAGENTO_SAMPLE_DATA_PATH $SETUP_CACHE_MAGENTO_SAMPLE_DATA_URL
+        # Check sample data md5
         - SUM=$(md5sum $SETUP_CACHE_MAGENTO_SAMPLE_DATA_PATH | awk '{print $1;}' )
-        - CHECKSUM_VAR_NAME=$(echo "SETUP_CACHE_MAGENTO_SAMPLE_DATA_CHECKSUM_${SETUP_CACHE_MAGENTO_SAMPLE_DATA_VERSION}_MD5" | sed 's/\.//g')
-        - CHECKSUM="$(eval "echo \$$CHECKSUM_VAR_NAME")"
-    
-    - title: "Check sample data md5"
-      shell_condition: '"$SUM" != "$CHECKSUM"'
-      commands:
-        - echo "### Sample data download failed"
-        - echo "Url $SETUP_CACHE_MAGENTO_SAMPLE_DATA_URL "
-        - echo "Sum $SUM "
-        - echo "Checksum $CHECKSUM "
-        - exit 1
-        
+        - CHECKSUM="$(echo "\$SETUP_CACHE_MAGENTO_SAMPLE_DATA_CHECKSUM_${SETUP_CACHE_MAGENTO_SAMPLE_DATA_VERSION}_MD5" | sed 's/\.//g' | envsubst )"
+        - if [ "$SUM" != "$CHECKSUM" ]; then
+            echo "### Sample data download failed";
+            echo "$SUM != $CHECKSUM";
+            exit 1;
+          fi
+
 #
 # Config process run just before the entrypoint
 #
@@ -103,7 +99,7 @@ config:
           valueFromParse: $SETUP_CACHE_MAGENTO_SAMPLE_DATA_VERSION
         install: True
         url: "'https://netcologne.dl.sourceforge.net/project/mageloads/assets/${CONFIG_SAMPLE_DATA_VERSION}/magento-sample-data-${CONFIG_SAMPLE_DATA_VERSION}.zip'"
-        path: "/tmp/magento-sample-data-${CONFIG_SAMPLE_DATA_VERSION}.zip"
+        path: "'/tmp/magento-sample-data-${CONFIG_SAMPLE_DATA_VERSION}.zip'"
     admin:
       username: "admin"
       lastname: "Admin"
@@ -165,6 +161,11 @@ config:
       init: "yes"
 
   processes:
+    - title: Expand var in env vars
+      commands:
+        - export CONFIG_SAMPLE_DATA_PATH=$(echo "$CONFIG_SAMPLE_DATA_PATH" | envsubst)
+        - export CONFIG_SAMPLE_DATA_URL=$(echo "$CONFIG_SAMPLE_DATA_URL" | envsubst)
+    
     - title: "Install mage-install script "
       commands:
         - mkdir -p $( dirname ${CONFIG_MAGENTO_INSTALL_SCRIPT_PATH})
@@ -195,12 +196,12 @@ config:
       commands:
         # Download sample data
         - if [ "$BUILD_ENV" != "cached" ]; then
-            echo "-o $CONFIG_SAMPLE_DATA_PATH $CONFIG_SAMPLE_DATA_URL" | envsubst | xargs -exec curl;
+            curl -o $CONFIG_SAMPLE_DATA_PATH $CONFIG_SAMPLE_DATA_URL;
             if [ "$SETUP_CACHE_MAGENTO_SAMPLE_DATA_VERSION" = "$CONFIG_SAMPLE_DATA_VERSION" ]; then
               SUM=$(md5sum $CONFIG_SAMPLE_DATA_PATH | awk '{print $1;}' );
               if [ "ddb2103137e257006e30b66122caa999" != "$SUM" ]; then
                   echo "Checksum verification failed on sample data";
-                  exit 1;
+                  exit 1; 
               fi;
             fi;
           fi
